//
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});

// exported helper for runtime: set PRISMA_ACCELERATOR=1 to enable accelerator-aware code paths
// export const usePrismaAccelerator = process.env.PRISMA_ACCELERATOR === "1";
